; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	esp32async/AsyncTCP@^3.5.0
	esp32async/ESPAsyncWebServer@^3.12.0
	tzapu/WiFiManager@^2.0.17
lib_ignore = ESPAsyncTCP, RPAsyncTCP
monitor_speed = 115200

[env:UART]
;upload_protocol = espota
;upload_port = 10.85.192.18	


[env:OTA]
upload_protocol = espota
upload_port = 10.85.192.17
